/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as workoutNewImport } from './routes/(workout)/new'

// Create/Update Routes

const workoutNewRoute = workoutNewImport.update({
  id: '/(workout)/new',
  path: '/new',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(workout)/new': {
      id: '/(workout)/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof workoutNewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/new': typeof workoutNewRoute
}

export interface FileRoutesByTo {
  '/new': typeof workoutNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(workout)/new': typeof workoutNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/new'
  id: '__root__' | '/(workout)/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  workoutNewRoute: typeof workoutNewRoute
}

const rootRouteChildren: RootRouteChildren = {
  workoutNewRoute: workoutNewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(workout)/new"
      ]
    },
    "/(workout)/new": {
      "filePath": "(workout)/new.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
