jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is fetched for accurate changes detection

      # Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install dependencies and build
      - name: Install Dependencies and Build
        run: |
          bun install
          bun run build
        env:
          CI: true # Ensure Bun treats this as a CI build

      # Prevent errors from uncommitted changes
      - name: Reset Git Changes
        run: |
          git reset --hard HEAD
          git clean -fd

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./dist
