name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace 'main' with your default branch name if different

  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install dependencies and build
      - name: Install Dependencies and Build
        run: |
          bun install
          bun run build # Replace with your actual build script if different

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Replace with your actual output directory if different
