name: Deploy PWA to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch name
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install
        env:
          CI: true

      - name: Build
        run: bun run build
        env:
          CI: true
          BASE_URL: '/${{ github.event.repository.name }}'  # For correct asset paths in GitHub Pages

      # Configure PWA assets
      - name: Configure PWA
        run: |
          cp dist/manifest.webmanifest dist/manifest.json || true
          cp -r public/* dist/ || true

      # Reset Git Changes
      - name: Reset Git Changes
        run: |
          git reset --hard HEAD
          git clean -fd

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  
          publish_dir: ./dist
          force_orphan: true  # Keep only latest commit in gh-pages branch
          enable_jekyll: false